# run with:
# `docker compose up --abort-on-container-exit --exit-code-from test_client`
#
# When the container stop prematurely, do a full `docker compose down` and `docker compose up` as caching can cause errors

version: "3"

services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - certs_ca:/certs/ca
      - certs_client:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      common:
        aliases:
          - docker

  test_client:
    image: docker:latest
    volumes:
      - certs_client:/certs/client:ro
      - .:/app_origin:ro
      - ./plugin/config.json:/plugin/config.json:ro
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    entrypoint: ["/app_origin/test_client_entrypoint.sh"]
    networks:
      common:
        aliases:
          # apparently underscores aren't allowed (ノಠ益ಠ)ノ彡┻━┻
          - test-client
    depends_on:
      - dind

networks:
  common:

volumes:
  certs_ca:
  certs_client:

