name: docker_logdna CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t rootfsimage .

