name: docker_logdna CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Install Rust
        run: |
          apt-get update
          apt-get install -y musl-tools musl-dev protobuf-compiler
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup target add x86_64-unknown-linux-musl
          rustup component add clippy

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clippy
        run: |
          . "$HOME/.cargo/env"
          cargo clippy -- -W clippy::unwrap_used -A clippy::useless_format -D warnings

      - name: Test Debug
        run: |
          . "$HOME/.cargo/env"
          cargo test

      - name: Test Release
        run: |
          . "$HOME/.cargo/env"
          cargo test --release

      - name: Build Release
        run: |
          . "$HOME/.cargo/env"
          cargo build --release --target x86_64-unknown-linux-musl

