name: docker_logdna CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustup update

      - name: Build and Test Plugin
        run: |
          if docker plugin ls | grep logdna:latest; then
              docker plugin disable -f logdna:latest || true
              docker plugin remove -f logdna:latest || true
          fi

          mkdir ./plugin/rootfs
          docker build -t rootfsimage .
          docker export $(docker create rootfsimage true) | tar -x -C ./plugin/rootfs
          docker plugin create logdna ./plugin
          rm -r ./plugin/rootfs
          docker plugin enable logdna

      - name: Build Mock Client
        run: |
          cd $GITHUB_WORKSPACE/mock/client
          docker build -t mock_client -f Dockerfile ..

      - name: Build Mock Server
        run: |
          source "$HOME/.cargo/env"
          cd $GITHUB_WORKSPACE/mock/server
          cargo build

      - name: Build Dind Test Driver
        run: |
          source "$HOME/.cargo/env"
          cd $GITHUB_WORKSPACE/dind_test_driver
          cargo build
