name: docker_logdna CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # - name: Run Docker-in-Docker End-to-End Test
      #   run: |
      #     docker compose up

      - name: Run Docker-in-Docker End-to-End Test
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--abort-on-container-exit --exit-code-from test_client"

