name: docker_logdna CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Docker-in-Docker End-to-End Test
        run: |
          docker compose up

